In [2]:
from pmbrl.data import Experiment_Data

In [2]:
data1 = Experiment_Data()

data1.generate_episodes(3)
data1.save(path='testing_data_short.csv')

/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(

In [3]:
data2 = Experiment_Data()

data2.generate_episodes(10)
data2.save(path='training_data_short.csv')

/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(

In [4]:
data2.raw_data.head()

,step,s,a,r,s_,p,episode
0,0,"[-0.041, 0.037, 0.015, -0.0]",0,1.0,"[-0.04, -0.157, 0.015, 0.276]","[0.24, 0.6]",0
1,1,"[-0.04, -0.157, 0.015, 0.276]",1,1.0,"[-0.043, 0.037, 0.02, 0.009]","[0.24, 0.6]",0
2,2,"[-0.043, 0.037, 0.02, 0.009]",1,1.0,"[-0.042, 0.231, 0.02, -0.257]","[0.24, 0.6]",0
3,3,"[-0.042, 0.231, 0.02, -0.257]",1,1.0,"[-0.038, 0.425, 0.015, -0.523]","[0.24, 0.6]",0
4,4,"[-0.038, 0.425, 0.015, -0.523]",0,1.0,"[-0.029, 0.23, 0.005, -0.247]","[0.24, 0.6]",0

In [2]:
training_data = Experiment_Data()

training_data.load(path='training_data.csv')
training_data.raw_data.head()

,episode,step,s,a,r,s_,p
0,0,0,"(0.02, -0.037, -0.022, 0.009)",0,1.0,"(0.019, -0.229, -0.022, 0.229)","(0.58, 1.0)"
1,0,1,"(0.019, -0.229, -0.022, 0.229)",0,1.0,"(0.015, -0.421, -0.017, 0.449)","(0.58, 1.0)"
2,0,2,"(0.015, -0.421, -0.017, 0.449)",0,1.0,"(0.006, -0.612, -0.008, 0.671)","(0.58, 1.0)"
3,0,3,"(0.006, -0.612, -0.008, 0.671)",0,1.0,"(-0.006, -0.804, 0.005, 0.894)","(0.58, 1.0)"
4,0,4,"(-0.006, -0.804, 0.005, 0.894)",1,1.0,"(-0.022, -0.612, 0.023, 0.67)","(0.58, 1.0)"

# Stats

In [11]:
data = Experiment_Data()

# data.load(path='testing_data.csv')
data.load(path='training_data.csv')
data.raw_data.head()

,episode,step,s,a,r,s_,p
0,0,0,"(0.02, -0.037, -0.022, 0.009)",0,1.0,"(0.019, -0.229, -0.022, 0.229)","(0.58, 1.0)"
1,0,1,"(0.019, -0.229, -0.022, 0.229)",0,1.0,"(0.015, -0.421, -0.017, 0.449)","(0.58, 1.0)"
2,0,2,"(0.015, -0.421, -0.017, 0.449)",0,1.0,"(0.006, -0.612, -0.008, 0.671)","(0.58, 1.0)"
3,0,3,"(0.006, -0.612, -0.008, 0.671)",0,1.0,"(-0.006, -0.804, 0.005, 0.894)","(0.58, 1.0)"
4,0,4,"(-0.006, -0.804, 0.005, 0.894)",1,1.0,"(-0.022, -0.612, 0.023, 0.67)","(0.58, 1.0)"

In [12]:
from pmbrl.data import get_data_expanded

expansions = {
    'p': ['p0', 'p1'],
}

df = get_data_expanded(data.raw_data, expansions)
df.head()

,episode,step,s,a,r,s_,p,p0,p1
0,0,0,"(0.02, -0.037, -0.022, 0.009)",0,1.0,"(0.019, -0.229, -0.022, 0.229)","(0.58, 1.0)",0.58,1.0
1,0,1,"(0.019, -0.229, -0.022, 0.229)",0,1.0,"(0.015, -0.421, -0.017, 0.449)","(0.58, 1.0)",0.58,1.0
2,0,2,"(0.015, -0.421, -0.017, 0.449)",0,1.0,"(0.006, -0.612, -0.008, 0.671)","(0.58, 1.0)",0.58,1.0
3,0,3,"(0.006, -0.612, -0.008, 0.671)",0,1.0,"(-0.006, -0.804, 0.005, 0.894)","(0.58, 1.0)",0.58,1.0
4,0,4,"(-0.006, -0.804, 0.005, 0.894)",1,1.0,"(-0.022, -0.612, 0.023, 0.67)","(0.58, 1.0)",0.58,1.0

In [13]:
count_p0 = float(df.p0.unique().shape[0])
count_p1 = float(df.p1.unique().shape[0])
avg_p0 = float(df.p0.unique().mean())
avg_p1 = float(df.p1.unique().mean())
std_p0 = float(df.p0.unique().std())
std_p1 = float(df.p1.unique().std())
max_p0 = float(df.p0.unique().max())
max_p1 = float(df.p1.unique().max())
min_p0 = float(df.p0.unique().min())
min_p1 = float(df.p1.unique().min())

print(f"{count_p0 = }")
print(f"{avg_p0 = }")
print(f"{std_p0 = }")
print(f"{max_p0 = }")
print(f"{min_p0 = }")
print(f"{count_p1 = }")
print(f"{avg_p1 = }")
print(f"{std_p1 = }")
print(f"{max_p1 = }")
print(f"{min_p1 = }")

count_p0 = 58.0
avg_p0 = 0.5227586206896552
std_p0 = 0.2825364981210592
max_p0 = 0.99
min_p0 = 0.01
count_p1 = 20.0
avg_p1 = 0.95
std_p1 = 0.5766281297335398
max_p1 = 1.9
min_p1 = 0.0

In [27]:
c = df.loc[df.step==0].groupby(['p0','p1']).count()#.sort_values(by='episode')
c.loc[c.p>1]

          episode  step  s  a  r  s_  p
p0   p1
0.03 0.9        2     2  2  2  2   2  2
0.07 0.4        2     2  2  2  2   2  2
0.36 0.2        2     2  2  2  2   2  2
0.58 1.0        2     2  2  2  2   2  2
0.77 1.4        2     2  2  2  2   2  2

In [26]:
df.loc[(df.p0==0.77) & (df.p1==1.4	)]

,episode,step,s,a,r,s_,p,p0,p1
1651,68,0,"(-0.002, 0.035, 0.017, 0.013)",1,1.0,"(-0.001, 0.226, 0.018, -0.189)","(0.77, 1.4)",0.77,1.4
1652,68,1,"(-0.001, 0.226, 0.018, -0.189)",0,1.0,"(0.004, 0.034, 0.014, 0.02)","(0.77, 1.4)",0.77,1.4
1653,68,2,"(0.004, 0.034, 0.014, 0.02)",0,1.0,"(0.004, -0.157, 0.014, 0.228)","(0.77, 1.4)",0.77,1.4
1654,68,3,"(0.004, -0.157, 0.014, 0.228)",0,1.0,"(0.001, -0.348, 0.019, 0.437)","(0.77, 1.4)",0.77,1.4
1655,68,4,"(0.001, -0.348, 0.019, 0.437)",0,1.0,"(-0.006, -0.539, 0.028, 0.646)","(0.77, 1.4)",0.77,1.4
1656,68,5,"(-0.006, -0.539, 0.028, 0.646)",0,1.0,"(-0.017, -0.731, 0.04, 0.857)","(0.77, 1.4)",0.77,1.4
1657,68,6,"(-0.017, -0.731, 0.04, 0.857)",0,1.0,"(-0.031, -0.922, 0.058, 1.07)","(0.77, 1.4)",0.77,1.4
1658,68,7,"(-0.031, -0.922, 0.058, 1.07)",0,1.0,"(-0.05, -1.114, 0.079, 1.287)","(0.77, 1.4)",0.77,1.4
1659,68,8,"(-0.05, -1.114, 0.079, 1.287)",1,1.0,"(-0.072, -0.923, 0.105, 1.101)","(0.77, 1.4)",0.77,1.4
1660,68,9,"(-0.072, -0.923, 0.105, 1.101)",0,1.0,"(-0.09, -1.115, 0.127, 1.325)","(0.77, 1.4)",0.77,1.4
1661,68,10,"(-0.09, -1.115, 0.127, 1.325)",0,1.0,"(-0.113, -1.307, 0.153, 1.552)","(0.77, 1.4)",0.77,1.4
1662,68,11,"(-0.113, -1.307, 0.153, 1.552)",1,1.0,"(-0.139, -1.118, 0.184, 1.387)","(0.77, 1.4)",0.77,1.4
1663,68,12,"(-0.139, -1.118, 0.184, 1.387)",1,1.0,"(-0.161, -0.929, 0.212, 1.231)","(0.77, 1.4)",0.77,1.4
2202,91,0,"(-0.022, 0.041, 0.032, -0.021)",1,1.0,"(-0.021, 0.232, 0.032, -0.218)","(0.77, 1.4)",0.77,1.4
2203,91,1,"(-0.021, 0.232, 0.032, -0.218)",0,1.0,"(-0.016, 0.04, 0.027, -0.007)","(0.77, 1.4)",0.77,1.4
2204,91,2,"(-0.016, 0.04, 0.027, -0.007)",1,1.0,"(-0.015, 0.231, 0.027, -0.206)","(0.77, 1.4)",0.77,1.4
2205,91,3,"(-0.015, 0.231, 0.027, -0.206)",0,1.0,"(-0.011, 0.04, 0.023, 0.005)","(0.77, 1.4)",0.77,1.4
2206,91,4,"(-0.011, 0.04, 0.023, 0.005)",0,1.0,"(-0.01, -0.152, 0.023, 0.215)","(0.77, 1.4)",0.77,1.4
2207,91,5,"(-0.01, -0.152, 0.023, 0.215)",0,1.0,"(-0.013, -0.343, 0.027, 0.425)","(0.77, 1.4)",0.77,1.4
2208,91,6,"(-0.013, -0.343, 0.027, 0.425)",0,1.0,"(-0.02, -0.534, 0.036, 0.636)","(0.77, 1.4)",0.77,1.4
2209,91,7,"(-0.02, -0.534, 0.036, 0.636)",1,1.0,"(-0.031, -0.343, 0.049, 0.439)","(0.77, 1.4)",0.77,1.4
2210,91,8,"(-0.031, -0.343, 0.049, 0.439)",1,1.0,"(-0.037, -0.153, 0.057, 0.246)","(0.77, 1.4)",0.77,1.4
2211,91,9,"(-0.037, -0.153, 0.057, 0.246)",0,1.0,"(-0.041, -0.345, 0.062, 0.462)","(0.77, 1.4)",0.77,1.4
2212,91,10,"(-0.041, -0.345, 0.062, 0.462)",0,1.0,"(-0.047, -0.536, 0.071, 0.68)","(0.77, 1.4)",0.77,1.4
2213,91,11,"(-0.047, -0.536, 0.071, 0.68)",0,1.0,"(-0.058, -0.728, 0.085, 0.899)","(0.77, 1.4)",0.77,1.4
2214,91,12,"(-0.058, -0.728, 0.085, 0.899)",0,1.0,"(-0.073, -0.92, 0.103, 1.12)","(0.77, 1.4)",0.77,1.4
2215,91,13,"(-0.073, -0.92, 0.103, 1.12)",0,1.0,"(-0.091, -1.112, 0.125, 1.344)","(0.77, 1.4)",0.77,1.4
2216,91,14,"(-0.091, -1.112, 0.125, 1.344)",0,1.0,"(-0.113, -1.303, 0.152, 1.571)","(0.77, 1.4)",0.77,1.4
2217,91,15,"(-0.113, -1.303, 0.152, 1.571)",1,1.0,"(-0.139, -1.114, 0.184, 1.406)","(0.77, 1.4)",0.77,1.4
2218,91,16,"(-0.139, -1.114, 0.184, 1.406)",1,1.0,"(-0.162, -0.925, 0.212, 1.25)","(0.77, 1.4)",0.77,1.4