# $(SASA) Regular$

$loss = \alpha \times mse(\hat{\theta_i^a}, \hat{\theta_j^a}) + \beta \times (1-mse(\hat{\theta_i^a}, \hat{\theta_k^b})) + \gamma \times mse(\hat{s_{i+2}^a}, y) + \lambda(\hat{\theta_i^a}^2 + \hat{\theta_k^b}^2 + \hat{\theta_j^a}^2)$

## Experimento Validação

- 100 episódios de Treino
- 10 episódios de Validação
- 1 agente

* Cada agente é treinado com 800 passos dos episódios de treino e testado em 200, os passos de todos os episodios sao embaralhados aleatoriamente
* Resultado intermedário é uma comparacao do parametro estimado em cada passo de teste com o parametro real
* Os a gentes são validados em cada passo dos episódios de validação
* Resultado final é comparacao do parametro estimado em cada passo pelos agentes com o parametro real

In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model, Regularized_Reference_Loss_Normalized, Regularized_Reference_Loss
from pmbrl.data import Experiment_Data, get_data_expanded

# Training

In [2]:
data = Experiment_Data()

data.load(path='../training_data.csv')
data.build_training_dataset()

,step,episode,p,s,a,r,s_,a_,r_,s__
735,9,26,"(0.2353791242085411, 0.7095048192803978)","(-0.036, -0.217, -0.008, 0.203)",1,1.0,"(-0.04, -0.024, -0.004, -0.028)",1.0,1.0,"(-0.041, 0.168, -0.005, -0.258)"
1479,4,59,"(0.0516954554163139, 0.1524358046184122)","(-0.006, 0.036, 0.031, -0.097)",1,1.0,"(-0.006, 0.259, 0.029, -0.993)",0.0,1.0,"(-0.0, 0.034, 0.009, -0.037)"
918,3,38,"(0.4545373771214862, 0.5810082803318615)","(0.001, -0.223, 0.017, 0.376)",0,1.0,"(-0.003, -0.421, 0.024, 0.722)",1.0,1.0,"(-0.012, -0.224, 0.038, 0.391)"
104,16,5,"(0.3551867425587211, 0.959194989729514)","(-0.005, -0.349, 0.036, 0.339)",0,1.0,"(-0.012, -0.54, 0.043, 0.534)",0.0,1.0,"(-0.023, -0.731, 0.053, 0.73)"
1583,5,65,"(0.1785778102029531, 1.438381745613701)","(-0.06, 0.189, -0.007, -0.141)",1,1.0,"(-0.056, 0.376, -0.01, -0.25)",1.0,1.0,"(-0.049, 0.562, -0.015, -0.359)"
...,...,...,...,...,...,...,...,...,...,...
2183,5,85,"(0.2714262518980411, 0.6857384251475167)","(-0.069, -0.196, 0.025, 0.247)",0,1.0,"(-0.073, -0.389, 0.03, 0.498)",1.0,1.0,"(-0.081, -0.197, 0.04, 0.262)"
935,20,38,"(0.4545373771214862, 0.5810082803318615)","(0.033, -0.039, 0.001, 0.321)",1,1.0,"(0.033, 0.158, 0.007, -0.019)",0.0,1.0,"(0.036, -0.039, 0.007, 0.324)"
1198,0,49,"(0.3032155985016214, 0.5787433112675132)","(-0.014, 0.009, -0.011, 0.012)",1,1.0,"(-0.014, 0.205, -0.011, -0.288)",1.0,1.0,"(-0.009, 0.4, -0.016, -0.588)"
1386,1,57,"(0.4858968354133477, 0.4002511587990111)","(0.018, 0.201, 0.034, -0.506)",1,1.0,"(0.022, 0.405, 0.024, -0.997)",1.0,1.0,"(0.03, 0.609, 0.004, -1.493)"
1023,5,42,"(0.0783299669233051, 0.1772545769968534)","(0.044, 0.645, -0.022, -2.309)",0,1.0,"(0.057, 0.427, -0.068, -1.515)",0.0,1.0,"(0.065, 0.211, -0.098, -0.763)"

In [3]:
nome_do_arquivo = 'features.pkl'

with open(nome_do_arquivo, 'rb') as arquivo:
    features = pickle.load(arquivo)
    x, y = features.values()

# x, y = model.get_features_targets(data.training_dataset)

In [4]:
# model = Model(transition_criterion_clss=Regularized_Reference_Loss_Normalized)
model = Model(transition_criterion_clss=Regularized_Reference_Loss)

loss_param=1e-5

# x, y = model.get_features_targets(data.training_dataset)
trainer = model.train(x, y, num_epochs=5000, alpha=loss_param, beta=loss_param, lambda_=loss_param)
train_data = data.get_training_data(trainer, inference_schema=model.inference_schema)
train_data.head()

,epoch,mse_positive,mse_negative,mse_s,regularize,transition,reward
0,0,"[0.20433543622493744, 0.7520138025283813]","[0.1986352801322937, 0.7772021889686584]","[0.027312278747558594, 0.5387204885482788, 0.0...",0.787461,1.351971,1.616515
1,1,"[0.20684629678726196, 0.7562749981880188]","[0.20115630328655243, 0.7817805409431458]","[0.026641221717000008, 0.5352749824523926, 0.0...",0.788160,1.340165,1.611921
2,2,"[0.2093905359506607, 0.7605405449867249]","[0.20371055603027344, 0.7863634824752808]","[0.026024119928479195, 0.531853199005127, 0.04...",0.788887,1.328536,1.607399
3,3,"[0.21197205781936646, 0.7648344039916992]","[0.20630209147930145, 0.7909740805625916]","[0.025461513549089432, 0.5284548401832581, 0.0...",0.789643,1.317084,1.602930
4,4,"[0.21459469199180603, 0.7691701054573059]","[0.20893189311027527, 0.7956278920173645]","[0.024952206760644913, 0.525078535079956, 0.04...",0.790431,1.305809,1.598475

In [5]:
data.training_dataset.head()

,step,episode,p,s,a,r,s_,a_,r_,s__
735,9,26,"(0.2353791242085411, 0.7095048192803978)","(-0.036, -0.217, -0.008, 0.203)",1,1.0,"(-0.04, -0.024, -0.004, -0.028)",1.0,1.0,"(-0.041, 0.168, -0.005, -0.258)"
1479,4,59,"(0.0516954554163139, 0.1524358046184122)","(-0.006, 0.036, 0.031, -0.097)",1,1.0,"(-0.006, 0.259, 0.029, -0.993)",0.0,1.0,"(-0.0, 0.034, 0.009, -0.037)"
918,3,38,"(0.4545373771214862, 0.5810082803318615)","(0.001, -0.223, 0.017, 0.376)",0,1.0,"(-0.003, -0.421, 0.024, 0.722)",1.0,1.0,"(-0.012, -0.224, 0.038, 0.391)"
104,16,5,"(0.3551867425587211, 0.959194989729514)","(-0.005, -0.349, 0.036, 0.339)",0,1.0,"(-0.012, -0.54, 0.043, 0.534)",0.0,1.0,"(-0.023, -0.731, 0.053, 0.73)"
1583,5,65,"(0.1785778102029531, 1.438381745613701)","(-0.06, 0.189, -0.007, -0.141)",1,1.0,"(-0.056, 0.376, -0.01, -0.25)",1.0,1.0,"(-0.049, 0.562, -0.015, -0.359)"

# Save

In [6]:
import pickle

exp = {
    "data": data,
    "model": model 
}

nome_do_arquivo = 'regular.pkl'
with open(nome_do_arquivo, 'wb') as arquivo:
    pickle.dump(exp, arquivo)

In [7]:
del data
del model