In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model
from pmbrl.data import Experiment_Data, get_data_expanded

In [2]:
nome_do_arquivo = 'regular_normilized.pkl'

with open(nome_do_arquivo, 'rb') as arquivo:
    exp = pickle.load(arquivo)
    data = exp['data']
    model = exp['model']

del exp
del arquivo

In [3]:
# data.evaluate_model(model, path='../testing_data(TEST).csv')
data.evaluate_model(model, path='../testing_data.csv')
results = data.get_evaluation_metrics()
results.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized,rse,rse_normalized
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,0.041,0.003,0.901,0.0,0.546990,0.536136,0.508393,0.511765,0.946,0.525821
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,0.067,0.007,1.008,0.0,0.548046,0.542527,0.517986,0.520921,1.084,0.532370
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,0.041,0.003,0.968,0.0,0.550158,0.536136,0.508393,0.517498,1.016,0.528046
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,0.052,0.001,0.917,0.0,0.552270,0.538840,0.503597,0.513134,0.976,0.526960
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,0.042,0.002,1.012,0.0,0.555438,0.536382,0.505995,0.521263,1.065,0.529769

In [4]:
results[['estimated_s', 'estimated_p']]

                         estimated_s      estimated_p
0     (-0.026, -0.484, 0.035, 1.633)  (-0.146, 0.146)
1     (-0.037, -0.355, 0.095, 2.334)  (-0.116, 0.142)
2     (-0.037, -0.491, 0.118, 1.726)   (-0.03, 0.241)
3      (-0.046, -0.352, 0.17, 2.518)  (-0.012, 0.235)
4     (-0.049, -0.504, 0.199, 2.033)   (0.075, 0.331)
...                              ...              ...
2122  (-0.107, -0.787, 0.128, 0.841)   (-0.075, 0.16)
2123   (-0.12, -0.973, 0.147, 1.286)  (-0.037, 0.219)
2124   (-0.14, -1.159, 0.171, 1.508)  (-0.026, 0.216)
2125  (-0.163, -1.343, 0.198, 1.729)  (-0.012, 0.215)
2126   (-0.189, -1.18, 0.227, 1.369)   (0.009, 0.222)

[2127 rows x 2 columns]

In [5]:
results[['rse', 'rse_normalized', 
       'rse_s0', 'rse_s1', 'rse_s2', 'rse_s3', 'rse_r', 'rse_s0_normalized',
       'rse_s1_normalized', 'rse_s2_normalized', 'rse_s3_normalized']].describe()

,rse,rse_normalized,rse_s0,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized
count,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.0,2127.000000,2127.000000,2127.000000,2127.000000
mean,0.192357,0.507811,0.002819,0.014575,0.000800,0.174162,0.0,0.548912,0.529640,0.503118,0.449573
std,0.220381,0.005796,0.003585,0.014559,0.001634,0.211500,0.0,0.003786,0.003579,0.003918,0.018097
min,0.003000,0.502201,0.000000,0.000000,0.000000,0.000000,0.0,0.545935,0.526057,0.501199,0.434671
25%,0.081000,0.504842,0.001000,0.005000,0.000000,0.065000,0.0,0.546990,0.527286,0.501199,0.440233
50%,0.132000,0.506382,0.002000,0.011000,0.001000,0.117000,0.0,0.548046,0.528761,0.503597,0.444682
75%,0.219000,0.508445,0.003000,0.019000,0.001000,0.197500,0.0,0.549102,0.530728,0.503597,0.451570
max,2.266000,0.566403,0.034000,0.152000,0.042000,2.129000,0.0,0.581837,0.563422,0.601918,0.616839

In [6]:
expansions = {
    'estimated_p': ['estimated_p0', 'estimated_p1'],
    's': ['s0', 's1', 's2', 's3'],
    's_': ['s_0', 's_1', 's_2', 's_3'],
    's__': ['s__0', 's__1', 's__2', 's__3'],
}


# df = data.evaluation_data[data.evaluation_data['episode'] == 98].copy().reset_index(drop=True)
df = data.evaluation_data.copy()
df = get_data_expanded(df, expansions)
df.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,s2,s3,s_0,s_1,s_2,s_3,s__0,s__1,s__2,s__3
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,0.013,-0.019,-0.019,-0.285,0.013,1.258,-0.025,-0.525,0.038,2.534
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,0.013,1.258,-0.025,-0.525,0.038,2.534,-0.035,-0.288,0.088,1.326
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,0.038,2.534,-0.035,-0.288,0.088,1.326,-0.041,-0.532,0.115,2.694
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,0.088,1.326,-0.041,-0.532,0.115,2.694,-0.052,-0.300,0.169,1.601
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,0.115,2.694,-0.052,-0.300,0.169,1.601,-0.058,-0.546,0.201,3.045

In [13]:
import torch
import torch.nn as nn
import torch.optim as optim

def find_params(m, inputs, target, initial_params, num_epochs=5000, learning_rate=.01):
    input_values = torch.tensor(inputs)#.reshape(1, len(inputs))
    param = torch.tensor(initial_params, requires_grad=True)
    target_value = torch.tensor(target)#.reshape(1, len(target))
    
    optimizer = optim.Adam([param], lr=learning_rate)
    criterion = nn.MSELoss(reduction='none')

    history = []

    for p in m.parameters():
        p.requires_grad = False

    for epoch in range(num_epochs):
        # Forward pass
        state_inputs = torch.concat([input_values, param.repeat((input_values.shape[0],1))], dim=1)
        output = m(state_inputs.float())  # Add batch dimension

        # Calculate the loss
        open_loss = criterion(output.float(), target_value.float())
        loss = torch.sqrt(open_loss.sum(axis=1).mean())
        

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        history.append((param.tolist(), output.tolist()[0], loss.item()))

        if (epoch + 1) % 100 == 0:
            # print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Input Param: {param.item():.4f}, Output: {output.item():.4f}')
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Input Param: {[round(p,4) for p in param.tolist()]}')
        return history

In [14]:
def optimize(row):
    epi_data = df.loc[(df['episode']==row.episode)&(df['step']<=row.step)].copy()

    m = model.transition_estimator.state_layer
    inputs = [[step.s0, step.s1, step.s2, step.s3, step.a] for _,step in epi_data.iterrows()]
    targets =[[step.s_0, step.s_1, step.s_2, step.s_3] for _,step in epi_data.iterrows()]
    init_param = [epi_data.estimated_p0.mean(), epi_data.estimated_p1.mean()]

    hist = find_params(m, inputs, targets, init_param)
    return hist[-1]

In [15]:
df[['new_estimated_p', 'new_estimated_s', 'param_rse']] = df.apply(lambda row: optimize(row), axis=1, result_type='expand')

In [16]:
df[['p', 'estimated_p', 'new_estimated_p']].head()

,p,estimated_p,new_estimated_p
0,"(0.5280280669895349, 0.1691488904272192)","(-0.146, 0.146)","[-0.13600001216012111, 0.13600000029149106]"
1,"(0.5280280669895349, 0.1691488904272192)","(-0.116, 0.142)","[-0.12100000510319336, 0.13400000032420933]"
2,"(0.5280280669895349, 0.1691488904272192)","(-0.03, 0.241)","[-0.1073333302006727, 0.1663333343805502]"
3,"(0.5280280669895349, 0.1691488904272192)","(-0.012, 0.235)","[-0.08599999420912534, 0.18100000070090078]"
4,"(0.5280280669895349, 0.1691488904272192)","(0.075, 0.331)","[-0.05579999698538966, 0.20900000195320126]"

In [17]:
expansions = {
    'new_estimated_p': ['new_estimated_p0', 'new_estimated_p1'],
}

final_df = data.evaluation_data.copy()
final_df = get_data_expanded(df, expansions)
final_df.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,s_3,s__0,s__1,s__2,s__3,new_estimated_p,new_estimated_s,param_rse,new_estimated_p0,new_estimated_p1
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,1.258,-0.025,-0.525,0.038,2.534,"[-0.13600001216012111, 0.13600000029149106]","[-0.010936334729194641, -0.25009414553642273, ...",0.952140,-0.136000,0.136000
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,2.534,-0.035,-0.288,0.088,1.326,"[-0.12100000510319336, 0.13400000032420933]","[-0.005278795957565308, -0.25196143984794617, ...",0.926323,-0.121000,0.134000
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,1.326,-0.041,-0.532,0.115,2.694,"[-0.1073333302006727, 0.1663333343805502]","[-0.009204909205436707, -0.2516958713531494, 0...",0.958351,-0.107333,0.166333
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,2.694,-0.052,-0.300,0.169,1.601,"[-0.08599999420912534, 0.18100000070090078]","[-0.009057432413101196, -0.25216802954673767, ...",0.959091,-0.086000,0.181000
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,1.601,-0.058,-0.546,0.201,3.045,"[-0.05579999698538966, 0.20900000195320126]","[-0.012109771370887756, -0.2518739700317383, 0...",0.955456,-0.055800,0.209000

In [ ]:
def predict(row):
    with torch.no_grad():
        m = model.transition_estimator.state_layer
        inputs = [row.s_0, row.s_1, row.s_2, row.s_3, row.a_]
        params = [row.new_estimated_p0, row.new_estimated_p1]

        input_values = torch.tensor(inputs).reshape(1, len(inputs))
        param = torch.tensor(params)

        for p in m.parameters():
            p.requires_grad = False

        state_inputs = torch.concat([input_values, param.reshape(1, len(params))], dim=1)
        output = m(state_inputs.float())  # Add batch dimension

    return [round(v, 3) for v in output.tolist()[0]]

In [19]:
final_df['new_estimated_s'] = final_df.apply(lambda row: predict(row), axis=1)

In [20]:
df_metrics = final_df.copy()
df_metrics['estimated_s'] = df_metrics['new_estimated_s']
results = data.get_evaluation_metrics(df_metrics)

In [25]:
final_df[['estimated_p', 'new_estimated_p']]

          estimated_p                              new_estimated_p
0     (-0.146, 0.146)  [-0.13600001216012111, 0.13600000029149106]
1     (-0.116, 0.142)  [-0.12100000510319336, 0.13400000032420933]
2      (-0.03, 0.241)    [-0.1073333302006727, 0.1663333343805502]
3     (-0.012, 0.235)  [-0.08599999420912534, 0.18100000070090078]
4      (0.075, 0.331)  [-0.05579999698538966, 0.20900000195320126]
...               ...                                          ...
2122   (-0.075, 0.16)  [-0.12999999310568108, 0.15418181748923732]
2123  (-0.037, 0.219)  [-0.12308332811315162, 0.16041666569760515]
2124  (-0.026, 0.216)  [-0.11638461027778643, 0.16546153759506665]
2125  (-0.012, 0.215)  [-0.10964285208428068, 0.16971428490046092]
2126   (0.009, 0.222)   [-0.10239999494279756, 0.1738666658750506]

[2127 rows x 2 columns]

In [22]:
final_df[['s__', 'estimated_s', 'new_estimated_s']]

,s__,estimated_s,new_estimated_s
0,"(-0.025, -0.525, 0.038, 2.534)","(-0.026, -0.484, 0.035, 1.633)","[-0.018, -0.486, 0.036, 1.636]"
1,"(-0.035, -0.288, 0.088, 1.326)","(-0.037, -0.355, 0.095, 2.334)","[-0.035, -0.356, 0.092, 2.336]"
2,"(-0.041, -0.532, 0.115, 2.694)","(-0.037, -0.491, 0.118, 1.726)","[-0.029, -0.491, 0.077, 1.746]"
3,"(-0.052, -0.3, 0.169, 1.601)","(-0.046, -0.352, 0.17, 2.518)","[-0.049, -0.357, 0.138, 2.53]"
4,"(-0.058, -0.546, 0.201, 3.045)","(-0.049, -0.504, 0.199, 2.033)","[-0.038, -0.504, 0.133, 2.07]"
...,...,...,...
2122,"(-0.105, -0.761, 0.128, 0.931)","(-0.107, -0.787, 0.128, 0.841)","[-0.121, -0.781, 0.109, 0.844]"
2123,"(-0.12, -0.952, 0.146, 1.156)","(-0.12, -0.973, 0.147, 1.286)","[-0.122, -0.967, 0.106, 1.303]"
2124,"(-0.139, -1.144, 0.169, 1.383)","(-0.14, -1.159, 0.171, 1.508)","[-0.147, -1.152, 0.131, 1.521]"
2125,"(-0.162, -1.336, 0.197, 1.615)","(-0.163, -1.343, 0.198, 1.729)","[-0.175, -1.334, 0.158, 1.741]"
2126,"(-0.189, -1.147, 0.229, 1.461)","(-0.189, -1.18, 0.227, 1.369)","[-0.203, -1.171, 0.182, 1.388]"

In [23]:
results[['rse', 'rse_normalized', 
       'rse_s0', 'rse_s1', 'rse_s2', 'rse_s3', 'rse_r', 'rse_s0_normalized',
       'rse_s1_normalized', 'rse_s2_normalized', 'rse_s3_normalized']].describe()

,rse,rse_normalized,rse_s0,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized
count,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.0,2127.000000,2127.000000,2127.000000,2127.000000
mean,0.235887,0.528900,0.014515,0.014636,0.030756,0.175980,0.0,0.561262,0.529655,0.574956,0.449729
std,0.221134,0.019487,0.013612,0.015161,0.027970,0.211827,0.0,0.014374,0.003727,0.067075,0.018125
min,0.013000,0.502788,0.000000,0.000000,0.000000,0.000000,0.0,0.545935,0.526057,0.501199,0.434671
25%,0.117000,0.513950,0.005000,0.005000,0.008000,0.061000,0.0,0.551214,0.527286,0.520384,0.439890
50%,0.181000,0.522549,0.011000,0.011000,0.021000,0.122000,0.0,0.557550,0.528761,0.551559,0.445110
75%,0.269500,0.539666,0.019000,0.018000,0.047500,0.207500,0.0,0.565998,0.530482,0.615108,0.452426
max,2.267000,0.610364,0.093000,0.157000,0.129000,2.133000,0.0,0.644139,0.564651,0.810552,0.617181

In [24]:
del model
del data