# $(SASA) Regular$

$loss = \alpha \times mse(\hat{\theta_i^a}, \hat{\theta_j^a}) + \beta \times (1-mse(\hat{\theta_i^a}, \hat{\theta_k^b})) + \gamma \times mse(\hat{s_{i+2}^a}, y) + \lambda(\hat{\theta_i^a}^2 + \hat{\theta_k^b}^2 + \hat{\theta_j^a}^2)$

## Experimento Validação

- 100 episódios de Treino
- 10 episódios de Validação
- 1 agente

* Cada agente é treinado com 800 passos dos episódios de treino e testado em 200, os passos de todos os episodios sao embaralhados aleatoriamente
* Resultado intermedário é uma comparacao do parametro estimado em cada passo de teste com o parametro real
* Os a gentes são validados em cada passo dos episódios de validação
* Resultado final é comparacao do parametro estimado em cada passo pelos agentes com o parametro real

In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model, Regularized_Reference_Loss_Normalized
from pmbrl.data import Experiment_Data, get_data_expanded

# Training

In [2]:
data = Experiment_Data()

data.load(path='../training_data.csv')
data.build_training_dataset()

,step,episode,p,s,a,r,s_,a_,r_,s__
1704,26,67,"(0.0550547819736606, 0.7277451834527079)","(-0.117, 0.332, 0.109, -0.142)",0,1.0,"(-0.11, 0.14, 0.106, 0.074)",0.0,1.0,"(-0.108, -0.051, 0.107, 0.29)"
1975,23,78,"(0.0956613712139894, 0.231794730405182)","(-0.017, -0.163, 0.07, 0.541)",0,1.0,"(-0.02, -0.376, 0.081, 1.216)",1.0,1.0,"(-0.028, -0.168, 0.105, 0.644)"
1097,8,45,"(0.0966014343877297, 0.3641500656519551)","(0.039, 0.4, -0.026, -0.707)",1,1.0,"(0.047, 0.601, -0.04, -1.118)",1.0,1.0,"(0.059, 0.801, -0.062, -1.536)"
89,1,5,"(0.3551867425587211, 0.959194989729514)","(0.031, 0.221, 0.001, -0.209)",1,1.0,"(0.036, 0.411, -0.003, -0.396)",0.0,1.0,"(0.044, 0.221, -0.011, -0.209)"
2238,3,88,"(0.4162542062822604, 0.4644156025476709)","(-0.024, -0.181, 0.012, 0.451)",0,1.0,"(-0.028, -0.382, 0.021, 0.866)",1.0,1.0,"(-0.035, -0.182, 0.039, 0.466)"
...,...,...,...,...,...,...,...,...,...,...
2343,7,93,"(0.2048148528652186, 0.3945260327599418)","(0.029, 0.202, 0.036, -0.362)",1,1.0,"(0.033, 0.402, 0.029, -0.748)",0.0,1.0,"(0.041, 0.201, 0.014, -0.334)"
2260,2,90,"(0.3414097641144769, 0.5159987201834333)","(-0.016, -0.377, 0.008, 0.682)",1,1.0,"(-0.024, -0.179, 0.022, 0.341)",1.0,1.0,"(-0.027, 0.018, 0.029, 0.005)"
2474,8,97,"(0.1358594884350926, 0.7069625486901497)","(-0.007, -0.39, 0.036, 0.489)",0,1.0,"(-0.014, -0.582, 0.046, 0.709)",0.0,1.0,"(-0.026, -0.774, 0.06, 0.932)"
2100,57,81,"(0.1825292152212203, 0.91730535067745)","(0.225, 0.13, 0.153, 0.532)",1,1.0,"(0.228, 0.318, 0.164, 0.392)",1.0,1.0,"(0.234, 0.506, 0.171, 0.255)"
2239,4,88,"(0.4162542062822604, 0.4644156025476709)","(-0.028, -0.382, 0.021, 0.866)",1,1.0,"(-0.035, -0.182, 0.039, 0.466)",1.0,1.0,"(-0.039, 0.018, 0.048, 0.073)"

In [3]:
nome_do_arquivo = 'features.pkl'

with open(nome_do_arquivo, 'rb') as arquivo:
    features = pickle.load(arquivo)
    x, y = features.values()

# x, y = model.get_features_targets(data.training_dataset)

In [4]:
model = Model(transition_criterion_clss=Regularized_Reference_Loss_Normalized)

loss_param=1e-5

# x, y = model.get_features_targets(data.training_dataset)
trainer = model.train(x, y, num_epochs=5000, alpha=loss_param, beta=loss_param, lambda_=loss_param)
train_data = data.get_training_data(trainer, inference_schema=model.inference_schema)
train_data.head()

,epoch,mse_positive,mse_negative,mse_s,regularize,transition,reward
0,0,"[0.0712934285402298, 0.46131420135498047]","[0.0689416453242302, 0.47757649421691895]","[0.010727571323513985, 0.02167285420000553, 0....",0.800654,0.315525,2.104223
1,1,"[0.07314931601285934, 0.46510928869247437]","[0.07074344158172607, 0.4813753664493561]","[0.010578400455415249, 0.021575219929218292, 0...",0.799466,0.306488,2.098326
2,2,"[0.07506629824638367, 0.46896597743034363]","[0.07260318100452423, 0.48522183299064636]","[0.010431274771690369, 0.021478302776813507, 0...",0.798321,0.297734,2.092460
3,3,"[0.07704535126686096, 0.4728633463382721]","[0.0745232105255127, 0.48910248279571533]","[0.01028541661798954, 0.021381458267569542, 0....",0.797225,0.289259,2.086645
4,4,"[0.07908941060304642, 0.47679078578948975]","[0.07650565356016159, 0.49300894141197205]","[0.010141112841665745, 0.0212844330817461, 0.2...",0.796181,0.281057,2.080883

In [5]:
data.training_dataset.head()

,step,episode,p,s,a,r,s_,a_,r_,s__
1704,26,67,"(0.0550547819736606, 0.7277451834527079)","(-0.117, 0.332, 0.109, -0.142)",0,1.0,"(-0.11, 0.14, 0.106, 0.074)",0.0,1.0,"(-0.108, -0.051, 0.107, 0.29)"
1975,23,78,"(0.0956613712139894, 0.231794730405182)","(-0.017, -0.163, 0.07, 0.541)",0,1.0,"(-0.02, -0.376, 0.081, 1.216)",1.0,1.0,"(-0.028, -0.168, 0.105, 0.644)"
1097,8,45,"(0.0966014343877297, 0.3641500656519551)","(0.039, 0.4, -0.026, -0.707)",1,1.0,"(0.047, 0.601, -0.04, -1.118)",1.0,1.0,"(0.059, 0.801, -0.062, -1.536)"
89,1,5,"(0.3551867425587211, 0.959194989729514)","(0.031, 0.221, 0.001, -0.209)",1,1.0,"(0.036, 0.411, -0.003, -0.396)",0.0,1.0,"(0.044, 0.221, -0.011, -0.209)"
2238,3,88,"(0.4162542062822604, 0.4644156025476709)","(-0.024, -0.181, 0.012, 0.451)",0,1.0,"(-0.028, -0.382, 0.021, 0.866)",1.0,1.0,"(-0.035, -0.182, 0.039, 0.466)"

# Save

In [6]:
import pickle

exp = {
    "data": data,
    "model": model 
}

nome_do_arquivo = 'regular_normilized.pkl'
with open(nome_do_arquivo, 'wb') as arquivo:
    pickle.dump(exp, arquivo)