In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model
from pmbrl.data import Experiment_Data, get_data_expanded

In [2]:
nome_do_arquivo = 'triplet.pkl'

with open(nome_do_arquivo, 'rb') as arquivo:
    exp = pickle.load(arquivo)
    data = exp['data']
    model = exp['model']

del exp
del arquivo

In [3]:
# data.evaluate_model(model, path='../testing_data(TEST).csv')
data.evaluate_model(model, path='../testing_data.csv')
results = data.get_evaluation_metrics()
results.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized,rse,rse_normalized
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,0.014,0.022,0.168,0.0,0.550158,0.529499,0.553957,0.449046,0.208,0.520665
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,0.050,0.022,0.121,0.0,0.565998,0.538348,0.553957,0.445024,0.212,0.525832
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,0.000,0.020,0.194,0.0,0.552270,0.526057,0.549161,0.451271,0.220,0.519690
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,0.030,0.007,0.045,0.0,0.561774,0.533432,0.517986,0.438521,0.097,0.512928
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,0.003,0.017,0.055,0.0,0.549102,0.526794,0.541966,0.439377,0.078,0.514310

In [4]:
results[['estimated_s', 'estimated_p']]

                         estimated_s      estimated_p
0     (-0.021, -0.511, 0.016, 2.702)  (0.982, -3.454)
1      (-0.016, -0.338, 0.11, 1.447)   (0.773, -3.32)
2     (-0.035, -0.532, 0.095, 2.888)  (0.731, -4.067)
3      (-0.037, -0.33, 0.176, 1.646)  (0.766, -3.666)
4       (-0.055, -0.543, 0.184, 3.1)  (0.461, -3.871)
...                              ...              ...
2122  (-0.117, -0.783, 0.123, 0.925)   (0.178, 0.856)
2123   (-0.103, -0.953, 0.15, 1.172)   (0.195, 0.918)
2124  (-0.121, -1.149, 0.176, 1.412)   (0.163, 0.856)
2125  (-0.143, -1.343, 0.206, 1.651)    (0.16, 0.875)
2126  (-0.197, -1.172, 0.229, 1.419)   (0.157, 0.884)

[2127 rows x 2 columns]

In [5]:
results[['rse', 'rse_normalized', 
       'rse_s0', 'rse_s1', 'rse_s2', 'rse_s3', 'rse_r', 'rse_s0_normalized',
       'rse_s1_normalized', 'rse_s2_normalized', 'rse_s3_normalized']].describe()

,rse,rse_normalized,rse_s0,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized
count,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.0,2127.000000,2127.000000,2127.000000,2127.000000
mean,0.047653,0.508197,0.007160,0.010738,0.005267,0.024488,0.0,0.553496,0.528697,0.513829,0.436766
std,0.051139,0.005134,0.008085,0.014691,0.004853,0.036386,0.0,0.008537,0.003611,0.011638,0.003113
min,0.003000,0.502401,0.000000,0.000000,0.000000,0.000000,0.0,0.545935,0.526057,0.501199,0.434671
25%,0.021000,0.505214,0.002000,0.003000,0.002000,0.007000,0.0,0.548046,0.526794,0.505995,0.435270
50%,0.033000,0.507033,0.005000,0.006000,0.004000,0.014000,0.0,0.551214,0.527532,0.510791,0.435869
75%,0.056000,0.509357,0.010000,0.012000,0.007000,0.028000,0.0,0.556494,0.529007,0.517986,0.437067
max,0.542000,0.566119,0.120000,0.189000,0.058000,0.388000,0.0,0.672650,0.572517,0.640288,0.467870

In [6]:
expansions = {
    'estimated_p': ['estimated_p0', 'estimated_p1'],
    's': ['s0', 's1', 's2', 's3'],
    's_': ['s_0', 's_1', 's_2', 's_3'],
    's__': ['s__0', 's__1', 's__2', 's__3'],
}


# df = data.evaluation_data[data.evaluation_data['episode'] == 98].copy().reset_index(drop=True)
df = data.evaluation_data.copy()
df = get_data_expanded(df, expansions)
df.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,s2,s3,s_0,s_1,s_2,s_3,s__0,s__1,s__2,s__3
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,0.013,-0.019,-0.019,-0.285,0.013,1.258,-0.025,-0.525,0.038,2.534
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,0.013,1.258,-0.025,-0.525,0.038,2.534,-0.035,-0.288,0.088,1.326
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,0.038,2.534,-0.035,-0.288,0.088,1.326,-0.041,-0.532,0.115,2.694
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,0.088,1.326,-0.041,-0.532,0.115,2.694,-0.052,-0.300,0.169,1.601
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,0.115,2.694,-0.052,-0.300,0.169,1.601,-0.058,-0.546,0.201,3.045

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim

def find_params(m, inputs, target, initial_params, num_epochs=5000, learning_rate=.01):
    input_values = torch.tensor(inputs)#.reshape(1, len(inputs))
    param = torch.tensor(initial_params, requires_grad=True)
    target_value = torch.tensor(target)#.reshape(1, len(target))
    
    optimizer = optim.Adam([param], lr=learning_rate)
    criterion = nn.MSELoss(reduction='none')

    history = []

    for p in m.parameters():
        p.requires_grad = False

    for epoch in range(num_epochs):
        # Forward pass
        state_inputs = torch.concat([input_values, param.repeat((input_values.shape[0],1))], dim=1)
        output = m(state_inputs.float())  # Add batch dimension

        # Calculate the loss
        open_loss = criterion(output.float(), target_value.float())
        loss = torch.sqrt(open_loss.sum(axis=1).mean())
        

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        history.append((param.tolist(), output.tolist()[0], loss.item()))

        if (epoch + 1) % 100 == 0:
            # print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Input Param: {param.item():.4f}, Output: {output.item():.4f}')
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Input Param: {[round(p,4) for p in param.tolist()]}')
        return history

In [8]:
def optimize(row):
    epi_data = df.loc[(df['episode']==row.episode)&(df['step']<=row.step)].copy()

    m = model.transition_estimator.state_layer
    inputs = [[step.s0, step.s1, step.s2, step.s3, step.a] for _,step in epi_data.iterrows()]
    targets =[[step.s_0, step.s_1, step.s_2, step.s_3] for _,step in epi_data.iterrows()]
    init_param = [epi_data.estimated_p0.mean(), epi_data.estimated_p1.mean()]

    hist = find_params(m, inputs, targets, init_param)
    return hist[-1]

In [9]:
df[['new_estimated_p', 'new_estimated_s', 'param_rse']] = df.apply(lambda row: optimize(row), axis=1, result_type='expand')

In [10]:
df[['p', 'estimated_p', 'new_estimated_p']].head()

,p,estimated_p,new_estimated_p
0,"(0.5280280669895349, 0.1691488904272192)","(0.982, -3.454)","[0.9720000008177245, -3.444000001031002]"
1,"(0.5280280669895349, 0.1691488904272192)","(0.773, -3.32)","[0.867500000641382, -3.3770000009312966]"
2,"(0.5280280669895349, 0.1691488904272192)","(0.731, -4.067)","[0.8186666678245379, -3.6036666676839397]"
3,"(0.5280280669895349, 0.1691488904272192)","(0.766, -3.666)","[0.8030000006757386, -3.6167500007565025]"
4,"(0.5280280669895349, 0.1691488904272192)","(0.461, -3.871)","[0.7326000021782142, -3.6656000012182623]"

In [11]:
expansions = {
    'new_estimated_p': ['new_estimated_p0', 'new_estimated_p1'],
}

final_df = data.evaluation_data.copy()
final_df = get_data_expanded(df, expansions)
final_df.head()

,step,episode,p,s,a,r,s_,a_,r_,s__,...,s_3,s__0,s__1,s__2,s__3,new_estimated_p,new_estimated_s,param_rse,new_estimated_p0,new_estimated_p1
0,0,0,"(0.5280280669895349, 0.1691488904272192)","(-0.018, -0.046, 0.013, -0.019)",0,1.0,"(-0.019, -0.285, 0.013, 1.258)",0.0,1.0,"(-0.025, -0.525, 0.038, 2.534)",...,1.258,-0.025,-0.525,0.038,2.534,"[0.9720000008177245, -3.444000001031002]","[-0.02947138249874115, -0.3243144750595093, 0....",0.043276,0.972000,-3.444000
1,1,0,"(0.5280280669895349, 0.1691488904272192)","(-0.019, -0.285, 0.013, 1.258)",0,1.0,"(-0.025, -0.525, 0.038, 2.534)",1.0,1.0,"(-0.035, -0.288, 0.088, 1.326)",...,2.534,-0.035,-0.288,0.088,1.326,"[0.867500000641382, -3.3770000009312966]","[-0.030031301081180573, -0.31928420066833496, ...",0.091946,0.867500,-3.377000
2,2,0,"(0.5280280669895349, 0.1691488904272192)","(-0.025, -0.525, 0.038, 2.534)",1,1.0,"(-0.035, -0.288, 0.088, 1.326)",0.0,1.0,"(-0.041, -0.532, 0.115, 2.694)",...,1.326,-0.041,-0.532,0.115,2.694,"[0.8186666678245379, -3.6036666676839397]","[-0.03027452528476715, -0.32398366928100586, 0...",0.105200,0.818667,-3.603667
3,3,0,"(0.5280280669895349, 0.1691488904272192)","(-0.035, -0.288, 0.088, 1.326)",0,1.0,"(-0.041, -0.532, 0.115, 2.694)",1.0,1.0,"(-0.052, -0.3, 0.169, 1.601)",...,2.694,-0.052,-0.300,0.169,1.601,"[0.8030000006757386, -3.6167500007565025]","[-0.030355408787727356, -0.32387053966522217, ...",0.108602,0.803000,-3.616750
4,4,0,"(0.5280280669895349, 0.1691488904272192)","(-0.041, -0.532, 0.115, 2.694)",1,1.0,"(-0.052, -0.3, 0.169, 1.601)",0.0,1.0,"(-0.058, -0.546, 0.201, 3.045)",...,1.601,-0.058,-0.546,0.201,3.045,"[0.7326000021782142, -3.6656000012182623]","[-0.030717112123966217, -0.32312285900115967, ...",0.098699,0.732600,-3.665600

In [12]:
def predict(row):
    with torch.no_grad():
        m = model.transition_estimator.state_layer
        inputs = [row.s_0, row.s_1, row.s_2, row.s_3, row.a_]
        params = [row.new_estimated_p0, row.new_estimated_p1]

        input_values = torch.tensor(inputs).reshape(1, len(inputs))
        param = torch.tensor(params)

        for p in m.parameters():
            p.requires_grad = False

        state_inputs = torch.concat([input_values, param.reshape(1, len(params))], dim=1)
        output = m(state_inputs.float())  # Add batch dimension

    return [round(v, 3) for v in output.tolist()[0]]

In [13]:
final_df['new_estimated_s'] = final_df.apply(lambda row: predict(row), axis=1)

In [14]:
df_metrics = final_df.copy()
df_metrics['estimated_s'] = df_metrics['new_estimated_s']
results = data.get_evaluation_metrics(df_metrics)

In [15]:
final_df[['estimated_p', 'new_estimated_p']]

          estimated_p                            new_estimated_p
0     (0.982, -3.454)   [0.9720000008177245, -3.444000001031002]
1      (0.773, -3.32)   [0.867500000641382, -3.3770000009312966]
2     (0.731, -4.067)  [0.8186666678245379, -3.6036666676839397]
3     (0.766, -3.666)  [0.8030000006757386, -3.6167500007565025]
4     (0.461, -3.871)  [0.7326000021782142, -3.6656000012182623]
...               ...                                        ...
2122   (0.178, 0.856)   [0.1972727294496352, 0.8966363607607112]
2123   (0.195, 0.918)  [0.19625000295691838, 0.8992499965146755]
2124   (0.163, 0.856)  [0.19292307916865511, 0.8966923049049216]
2125    (0.16, 0.875)  [0.18985714467147638, 0.8958571405830813]
2126   (0.157, 0.884)   [0.1870000015405915, 0.8957333314126639]

[2127 rows x 2 columns]

In [16]:
final_df[['s__', 'estimated_s', 'new_estimated_s']]

,s__,estimated_s,new_estimated_s
0,"(-0.025, -0.525, 0.038, 2.534)","(-0.021, -0.511, 0.016, 2.702)","[-0.021, -0.511, 0.016, 2.696]"
1,"(-0.035, -0.288, 0.088, 1.326)","(-0.016, -0.338, 0.11, 1.447)","[-0.015, -0.335, 0.11, 1.401]"
2,"(-0.041, -0.532, 0.115, 2.694)","(-0.035, -0.532, 0.095, 2.888)","[-0.035, -0.519, 0.094, 2.806]"
3,"(-0.052, -0.3, 0.169, 1.601)","(-0.037, -0.33, 0.176, 1.646)","[-0.036, -0.33, 0.177, 1.637]"
4,"(-0.058, -0.546, 0.201, 3.045)","(-0.055, -0.543, 0.184, 3.1)","[-0.05, -0.532, 0.18, 3.146]"
...,...,...,...
2122,"(-0.105, -0.761, 0.128, 0.931)","(-0.117, -0.783, 0.123, 0.925)","[-0.117, -0.782, 0.123, 0.925]"
2123,"(-0.12, -0.952, 0.146, 1.156)","(-0.103, -0.953, 0.15, 1.172)","[-0.103, -0.953, 0.15, 1.175]"
2124,"(-0.139, -1.144, 0.169, 1.383)","(-0.121, -1.149, 0.176, 1.412)","[-0.121, -1.147, 0.175, 1.413]"
2125,"(-0.162, -1.336, 0.197, 1.615)","(-0.143, -1.343, 0.206, 1.651)","[-0.143, -1.341, 0.205, 1.654]"
2126,"(-0.189, -1.147, 0.229, 1.461)","(-0.197, -1.172, 0.229, 1.419)","[-0.197, -1.169, 0.228, 1.414]"

In [17]:
results[['rse', 'rse_normalized', 
       'rse_s0', 'rse_s1', 'rse_s2', 'rse_s3', 'rse_r', 'rse_s0_normalized',
       'rse_s1_normalized', 'rse_s2_normalized', 'rse_s3_normalized']].describe()

,rse,rse_normalized,rse_s0,rse_s1,rse_s2,rse_s3,rse_r,rse_s0_normalized,rse_s1_normalized,rse_s2_normalized,rse_s3_normalized
count,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.000000,2127.0,2127.000000,2127.000000,2127.000000,2127.000000
mean,0.044648,0.508179,0.007307,0.010536,0.005299,0.021505,0.0,0.553651,0.528647,0.513907,0.436511
std,0.049607,0.005269,0.008261,0.014584,0.005025,0.034277,0.0,0.008723,0.003585,0.012051,0.002933
min,0.003000,0.502070,0.000000,0.000000,0.000000,0.000000,0.0,0.545935,0.526057,0.501199,0.434671
25%,0.020000,0.505267,0.002000,0.003000,0.002000,0.006000,0.0,0.548046,0.526794,0.505995,0.435184
50%,0.031000,0.506951,0.005000,0.006000,0.004000,0.012000,0.0,0.551214,0.527532,0.510791,0.435698
75%,0.053000,0.509273,0.010000,0.012000,0.007000,0.026000,0.0,0.556494,0.529007,0.517986,0.436896
max,0.659000,0.565796,0.119000,0.208000,0.055000,0.531000,0.0,0.671595,0.577188,0.633094,0.480106

In [18]:
del model
del data