# $(SASA) Regular$

$loss = \alpha \times mse(\hat{\theta_i^a}, \hat{\theta_j^a}) + \beta \times (1-mse(\hat{\theta_i^a}, \hat{\theta_k^b})) + \gamma \times mse(\hat{s_{i+2}^a}, y) + \lambda(\hat{\theta_i^a}^2 + \hat{\theta_k^b}^2 + \hat{\theta_j^a}^2)$

## Experimento Validação

- 100 episódios de Treino
- 10 episódios de Validação
- 1 agente

* Cada agente é treinado com 800 passos dos episódios de treino e testado em 200, os passos de todos os episodios sao embaralhados aleatoriamente
* Resultado intermedário é uma comparacao do parametro estimado em cada passo de teste com o parametro real
* Os a gentes são validados em cada passo dos episódios de validação
* Resultado final é comparacao do parametro estimado em cada passo pelos agentes com o parametro real

In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model, Triplet_Loss
from pmbrl.data import Experiment_Data, get_data_expanded

# Training

In [2]:
data = Experiment_Data()

data.load(path='../training_data.csv')
data.build_training_dataset()

,step,episode,p,s,a,r,s_,a_,r_,s__
505,57,19,"(0.0642916329828742, 1.239005358213764)","(0.026, 0.586, 0.081, 0.009)",0,1.0,"(0.038, 0.398, 0.081, 0.134)",0.0,1.0,"(0.046, 0.211, 0.084, 0.259)"
2068,25,81,"(0.1825292152212203, 0.91730535067745)","(-0.001, 0.526, 0.085, -0.204)",1,1.0,"(0.01, 0.715, 0.081, -0.358)",1.0,1.0,"(0.024, 0.904, 0.073, -0.512)"
2358,22,93,"(0.2048148528652186, 0.3945260327599418)","(0.046, 0.002, 0.022, 0.047)",0,1.0,"(0.046, -0.199, 0.023, 0.458)",0.0,1.0,"(0.042, -0.399, 0.032, 0.87)"
1804,9,71,"(0.101516037315209, 0.2595372644863228)","(-0.05, 0.602, 0.123, -1.179)",0,1.0,"(-0.038, 0.392, 0.099, -0.545)",1.0,1.0,"(-0.03, 0.596, 0.088, -1.047)"
1692,14,67,"(0.0550547819736606, 0.7277451834527079)","(-0.084, -0.42, 0.061, 0.395)",1,1.0,"(-0.092, -0.23, 0.069, 0.214)",1.0,1.0,"(-0.097, -0.04, 0.073, 0.034)"
...,...,...,...,...,...,...,...,...,...,...
2175,26,84,"(0.0433876892251688, 0.5641318888962644)","(0.014, 0.018, 0.154, 0.531)",0,1.0,"(0.014, -0.177, 0.164, 0.818)",0.0,1.0,"(0.01, -0.371, 0.181, 1.107)"
2015,9,80,"(0.077800491974935, 0.5006250071926374)","(-0.016, -0.239, -0.007, 0.213)",0,1.0,"(-0.021, -0.434, -0.003, 0.498)",1.0,1.0,"(-0.029, -0.239, 0.007, 0.21)"
2426,49,94,"(0.4377652476268179, 0.9729568415243506)","(0.415, 1.343, -0.151, -0.964)",0,1.0,"(0.442, 1.154, -0.17, -0.8)",0.0,1.0,"(0.465, 0.965, -0.186, -0.642)"
614,2,23,"(0.2125978932043111, 0.6111562190979459)","(0.024, 0.015, -0.044, -0.06)",1,1.0,"(0.024, 0.209, -0.045, -0.333)",0.0,1.0,"(0.028, 0.016, -0.052, -0.085)"
2445,15,95,"(0.0558866920316977, 1.0277254711695958)","(-0.145, -1.651, 0.082, 1.222)",0,1.0,"(-0.178, -1.839, 0.107, 1.372)",0.0,1.0,"(-0.215, -2.028, 0.134, 1.525)"

In [3]:
nome_do_arquivo = 'features.pkl'

with open(nome_do_arquivo, 'rb') as arquivo:
    features = pickle.load(arquivo)
    x, y = features.values()

# x, y = model.get_features_targets(data.training_dataset)

In [4]:
# model = Model(transition_criterion_clss=Regularized_Reference_Loss_Normalized)
model = Model(transition_criterion_clss=Triplet_Loss)

loss_param=1e-5

# x, y = model.get_features_targets(data.training_dataset)
trainer = model.train(x, y, num_epochs=5000, alpha=loss_param, beta=loss_param, lambda_=loss_param)
train_data = data.get_training_data(trainer, inference_schema=model.inference_schema)
train_data.head()

,epoch,triplet,mse_s,transition,reward
0,0,0.999133,"[0.06985348463058472, 0.37302061915397644, 0.1...",2.366019,2.003812
1,1,0.999072,"[0.06827308237552643, 0.3679906725883484, 0.10...",2.352044,1.996033
2,2,0.999010,"[0.06673020124435425, 0.36302828788757324, 0.1...",2.338202,1.988342
3,3,0.998940,"[0.06522329151630402, 0.3581339120864868, 0.10...",2.324493,1.980841
4,4,0.998868,"[0.06375277787446976, 0.3533095717430115, 0.10...",2.310918,1.973556

In [5]:
data.training_dataset.head()

,step,episode,p,s,a,r,s_,a_,r_,s__
505,57,19,"(0.0642916329828742, 1.239005358213764)","(0.026, 0.586, 0.081, 0.009)",0,1.0,"(0.038, 0.398, 0.081, 0.134)",0.0,1.0,"(0.046, 0.211, 0.084, 0.259)"
2068,25,81,"(0.1825292152212203, 0.91730535067745)","(-0.001, 0.526, 0.085, -0.204)",1,1.0,"(0.01, 0.715, 0.081, -0.358)",1.0,1.0,"(0.024, 0.904, 0.073, -0.512)"
2358,22,93,"(0.2048148528652186, 0.3945260327599418)","(0.046, 0.002, 0.022, 0.047)",0,1.0,"(0.046, -0.199, 0.023, 0.458)",0.0,1.0,"(0.042, -0.399, 0.032, 0.87)"
1804,9,71,"(0.101516037315209, 0.2595372644863228)","(-0.05, 0.602, 0.123, -1.179)",0,1.0,"(-0.038, 0.392, 0.099, -0.545)",1.0,1.0,"(-0.03, 0.596, 0.088, -1.047)"
1692,14,67,"(0.0550547819736606, 0.7277451834527079)","(-0.084, -0.42, 0.061, 0.395)",1,1.0,"(-0.092, -0.23, 0.069, 0.214)",1.0,1.0,"(-0.097, -0.04, 0.073, 0.034)"

# Save

In [6]:
import pickle

exp = {
    "data": data,
    "model": model 
}

nome_do_arquivo = 'triplet.pkl'
with open(nome_do_arquivo, 'wb') as arquivo:
    pickle.dump(exp, arquivo)

In [7]:
del data
del model