In [1]:
import matplotlib.pyplot as plt
import pickle

from pmbrl.model2 import Model
from pmbrl.data import Experiment_Data, get_data_expanded

In [2]:
data = Experiment_Data()

data.load(path='training_data_short.csv')
data.build_training_dataset()

,step,episode,p,s,a,r,s_,a_,r_,s__
34,4,3,"(0.05, 1.7)","(-0.058, -0.398, 0.038, 0.186)",0,1.0,"(-0.066, -0.584, 0.041, 0.272)",1.0,1.0,"(-0.078, -0.398, 0.047, 0.193)"
182,6,8,"(0.63, 0.6)","(0.025, 0.453, -0.09, -0.872)",1,1.0,"(0.034, 0.655, -0.107, -1.305)",0.0,1.0,"(0.047, 0.457, -0.133, -0.957)"
5,5,0,"(0.24, 0.6)","(-0.029, 0.23, 0.005, -0.247)",0,1.0,"(-0.025, 0.036, -0.0, 0.026)",0.0,1.0,"(-0.024, -0.158, 0.0, 0.298)"
59,29,3,"(0.05, 1.7)","(0.269, 1.271, -0.087, -0.539)",0,1.0,"(0.294, 1.086, -0.098, -0.464)",0.0,1.0,"(0.316, 0.901, -0.107, -0.39)"
55,25,3,"(0.05, 1.7)","(0.175, 0.899, -0.049, -0.351)",1,1.0,"(0.193, 1.085, -0.056, -0.439)",1.0,1.0,"(0.214, 1.271, -0.064, -0.527)"
...,...,...,...,...,...,...,...,...,...,...
189,2,9,"(0.11, 0.5)","(0.04, -0.022, 0.006, 0.034)",0,1.0,"(0.04, -0.217, 0.006, 0.331)",1.0,1.0,"(0.035, -0.022, 0.013, 0.038)"
126,42,5,"(0.63, 1.5)","(0.107, 0.037, -0.081, -0.158)",1,1.0,"(0.107, 0.227, -0.084, -0.33)",0.0,1.0,"(0.112, 0.038, -0.091, -0.186)"
57,27,3,"(0.05, 1.7)","(0.214, 1.271, -0.064, -0.527)",1,1.0,"(0.24, 1.456, -0.075, -0.615)",0.0,1.0,"(0.269, 1.271, -0.087, -0.539)"
47,17,3,"(0.05, 1.7)","(0.001, 0.899, 0.02, -0.344)",1,1.0,"(0.019, 1.084, 0.013, -0.425)",1.0,1.0,"(0.041, 1.27, 0.004, -0.507)"
120,36,5,"(0.63, 1.5)","(0.068, 0.034, -0.038, -0.102)",1,1.0,"(0.069, 0.224, -0.04, -0.268)",1.0,1.0,"(0.073, 0.413, -0.045, -0.434)"

In [3]:
model = Model()

loss_param=1e-5

x, y = model.get_features_targets(data.training_dataset)
trainer = model.train(x, y, num_epochs=2000, alpha=loss_param, beta=loss_param, lambda_=loss_param)
train_data = data.get_training_data(trainer, inference_schema=model.inference_schema)
train_data.head()

,epoch,mse_positive,mse_negative,mse_s,regularize,transition,reward
0,0,"[0.3340408205986023, 2.053555965423584]","[0.3669591248035431, 2.0486836433410645]","[0.03742280229926109, 0.5275488495826721, 0.16...",1.883746,1.566114,0.252804
1,1,"[0.33121296763420105, 2.05716872215271]","[0.3639458417892456, 2.0519611835479736]","[0.03677413612604141, 0.5223425030708313, 0.16...",1.884110,1.551680,0.250355
2,2,"[0.3284085690975189, 2.0608067512512207]","[0.36095142364501953, 2.0552780628204346]","[0.03614043444395065, 0.5171821713447571, 0.15...",1.884501,1.537383,0.247937
3,3,"[0.3256421983242035, 2.0644948482513428]","[0.3579959273338318, 2.0586466789245605]","[0.03552619740366936, 0.5120689272880554, 0.15...",1.884921,1.523221,0.245490
4,4,"[0.322929710149765, 2.0682532787323]","[0.3551056385040283, 2.06209397315979]","[0.0349324569106102, 0.5069986581802368, 0.153...",1.885372,1.509192,0.242962

In [4]:
data.training_dataset.head()

,step,episode,p,s,a,r,s_,a_,r_,s__
34,4,3,"(0.05, 1.7)","(-0.058, -0.398, 0.038, 0.186)",0,1.0,"(-0.066, -0.584, 0.041, 0.272)",1.0,1.0,"(-0.078, -0.398, 0.047, 0.193)"
182,6,8,"(0.63, 0.6)","(0.025, 0.453, -0.09, -0.872)",1,1.0,"(0.034, 0.655, -0.107, -1.305)",0.0,1.0,"(0.047, 0.457, -0.133, -0.957)"
5,5,0,"(0.24, 0.6)","(-0.029, 0.23, 0.005, -0.247)",0,1.0,"(-0.025, 0.036, -0.0, 0.026)",0.0,1.0,"(-0.024, -0.158, 0.0, 0.298)"
59,29,3,"(0.05, 1.7)","(0.269, 1.271, -0.087, -0.539)",0,1.0,"(0.294, 1.086, -0.098, -0.464)",0.0,1.0,"(0.316, 0.901, -0.107, -0.39)"
55,25,3,"(0.05, 1.7)","(0.175, 0.899, -0.049, -0.351)",1,1.0,"(0.193, 1.085, -0.056, -0.439)",1.0,1.0,"(0.214, 1.271, -0.064, -0.527)"

In [5]:

exp = {
    "data": data,
    "model": model 
}

nome_do_arquivo = 'exp.pkl'
with open(nome_do_arquivo, 'wb') as arquivo:
    pickle.dump(exp, arquivo)

In [6]:
del exp 
del data 
del model

In [7]:
with open(nome_do_arquivo, 'rb') as arquivo:
    exp = pickle.load(arquivo)
    data = exp['data']
    model = exp['model']

In [8]:
data.training_dataset.head()

,step,episode,p,s,a,r,s_,a_,r_,s__
34,4,3,"(0.05, 1.7)","(-0.058, -0.398, 0.038, 0.186)",0,1.0,"(-0.066, -0.584, 0.041, 0.272)",1.0,1.0,"(-0.078, -0.398, 0.047, 0.193)"
182,6,8,"(0.63, 0.6)","(0.025, 0.453, -0.09, -0.872)",1,1.0,"(0.034, 0.655, -0.107, -1.305)",0.0,1.0,"(0.047, 0.457, -0.133, -0.957)"
5,5,0,"(0.24, 0.6)","(-0.029, 0.23, 0.005, -0.247)",0,1.0,"(-0.025, 0.036, -0.0, 0.026)",0.0,1.0,"(-0.024, -0.158, 0.0, 0.298)"
59,29,3,"(0.05, 1.7)","(0.269, 1.271, -0.087, -0.539)",0,1.0,"(0.294, 1.086, -0.098, -0.464)",0.0,1.0,"(0.316, 0.901, -0.107, -0.39)"
55,25,3,"(0.05, 1.7)","(0.175, 0.899, -0.049, -0.351)",1,1.0,"(0.193, 1.085, -0.056, -0.439)",1.0,1.0,"(0.214, 1.271, -0.064, -0.527)"

In [9]:
data.evaluate_model(model, path='testing_data_short.csv')
results = data.get_evaluation_metrics()
results.head()

/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:168: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.deprecation(
/home/gui/Área de Trabalho/rlalgs/.venv/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:181: DeprecationWarning: WARN: Current gymnasium version requires that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.deprecation(

,step,episode,p,s,a,r,s_,a_,r_,s__,...,estimated_s3,p0,p1,estimated_p0,estimated_p1,rse_s0,rse_s1,rse_s2,rse_s3,rse_r
0,0,0,"(0.27, 1.9)","(-0.037, 0.026, -0.021, 0.016)",0,1.0,"(-0.036, -0.159, -0.02, 0.102)",0.0,1.0,"(-0.04, -0.345, -0.018, 0.188)",...,0.209,0.27,1.9,0.397,0.426,0.009,0.004,0.000,0.021,0.0
1,1,0,"(0.27, 1.9)","(-0.036, -0.159, -0.02, 0.102)",0,1.0,"(-0.04, -0.345, -0.018, 0.188)",0.0,1.0,"(-0.047, -0.531, -0.014, 0.274)",...,0.291,0.27,1.9,0.436,0.546,0.000,0.001,0.007,0.017,0.0
2,2,0,"(0.27, 1.9)","(-0.04, -0.345, -0.018, 0.188)",0,1.0,"(-0.047, -0.531, -0.014, 0.274)",1.0,1.0,"(-0.057, -0.345, -0.009, 0.185)",...,0.068,0.27,1.9,0.547,0.703,0.005,0.057,0.009,0.117,0.0
3,3,0,"(0.27, 1.9)","(-0.047, -0.531, -0.014, 0.274)",1,1.0,"(-0.057, -0.345, -0.009, 0.185)",0.0,1.0,"(-0.064, -0.531, -0.005, 0.272)",...,0.413,0.27,1.9,0.237,0.564,0.002,0.021,0.012,0.141,0.0
4,4,0,"(0.27, 1.9)","(-0.057, -0.345, -0.009, 0.185)",0,1.0,"(-0.064, -0.531, -0.005, 0.272)",1.0,1.0,"(-0.075, -0.345, 0.0, 0.183)",...,0.066,0.27,1.9,0.562,0.708,0.004,0.058,0.010,0.117,0.0